# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FQL_LeDongLi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 4.5'
  pod 'SnapKit', '~> 4.0.0'
  pod 'HandyJSON', '~> 4.0.0-beta.1'
  pod 'Kingfisher', '~> 4.2.0'
  pod 'MJRefresh', '~> 3.1.15'
#  pod 'Charts'     // 画数据图表
#  pod 'ChartsRealm'

  # Pods for FQL_LeDongLi

  target 'FQL_LeDongLiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
